Repository Picnic-GSM/GOOUT_SERVER, pull requests merged in 2021-09, with the labels that each got.

#20 #16/add redis module
  goout-server/package-lock.json
  goout-server/package.json
  goout-server/src/app.module.ts
  goout-server/src/register/register.controller.ts
  goout-server/src/register/register.module.ts
  goout-server/src/register/register.service.ts
  goout-server/src/util/authnum.service.ts
  goout-server/src/util/redis.service.ts
Labels: feature

#27 #13/redefine entity
  goout-api/src/leave/entites/leave.entity.ts
  goout-api/src/out/entities/out.entity.ts
  goout-api/src/user/entites/student.entity.ts
  goout-api/src/user/entites/teacher.entity.ts
Labels: enhancement

#29 #21/add cache manager module
  goout-api/package-lock.json
  goout-api/package.json
  goout-api/src/app.module.ts
  goout-api/src/leave/entites/leave.entity.ts
  goout-api/src/out/entities/out.entity.ts
  goout-api/src/out/out.service.ts
  goout-api/src/user/user.controller.ts
  goout-api/src/user/user.module.ts
  goout-api/src/user/user.service.ts
  goout-api/src/util/mail.ts
  goout-api/src/util/redis.ts
Labels: enhancement

#31 #26/feature student
  goout-api/Dockerfile
  goout-api/package-lock.json
  goout-api/package.json
  goout-api/src/app.module.ts
  goout-api/src/auth/auth.service.ts
  goout-api/src/database/database.providers.ts
  goout-api/src/leave/dto/create-leave.dto.ts
  goout-api/src/leave/entites/leave.entity.ts
  goout-api/src/leave/enum.ts
  goout-api/src/leave/leave.controller.ts
  goout-api/src/leave/leave.service.ts
  goout-api/src/out/dto/check-out-request.dto.ts
  goout-api/src/out/dto/create-out.dto.ts
  goout-api/src/out/dto/show-grade.dto.ts
  goout-api/src/out/entities/out.entity.ts
  goout-api/src/out/enum.ts
  goout-api/src/out/out.controller.ts
  goout-api/src/out/out.service.ts
  goout-api/src/user/dto/email-auth.dto.ts
  goout-api/src/user/dto/find-teacher-with-grade-class.dto.ts
  goout-api/src/user/dto/find-teacher-with-grade.dto.ts
  goout-api/src/user/dto/find-with-grade-class.dto.ts
  goout-api/src/user/dto/find-with-grade.dto.ts
  goout-api/src/user/dto/find-with-student-id.dto.ts
  goout-api/src/user/dto/login-teacher.dto.ts
  goout-api/src/user/dto/login.dto.ts
  goout-api/src/user/dto/send-email.dto.ts
  goout-api/src/user/entites/student.entity.ts
  goout-api/src/user/entites/teacher.entity.ts
  goout-api/src/user/user.controller.spec.ts
  goout-api/src/user/user.controller.ts
  goout-api/src/user/user.module.ts
  goout-api/src/user/user.service.ts
  goout-api/src/util/hash.ts
  goout-api/src/util/mailHandler.ts
  goout-api/src/util/redis.ts
Labels: feature

#36 docker-compose 추가
  goout-api/.dockerignore
  goout-api/Dockerfile
  goout-api/docker-compose.yaml
  goout-api/docker-entrypoint.sh
Labels: build
